export default {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  GET_COLLECTIONS_SUCCESS: 'GET_COLLECTIONS_SUCCESS',
  GET_COLLECTIONS_FAILURE: 'GET_COLLECTIONS_FAILURE',
  POST_COLLECTIONS_SUCCESS: 'POST_COLLECTIONS_SUCCESS',
  POST_COLLECTIONS_FAILURE: 'POST_COLLECTIONS_FAILURE',

};
